### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by AndreyKalashnik** [RobinKim-SWEngineer/FlutterDevelopment#2]
Add the splash screen with an image that reminds your Home, sweet Home :)

https://flutter.dev/docs/development/ui/advanced/splash-screen

**Comment by RobinKim-SWEngineer** [comment]
*Sweet home* screen :)

![screenShot](https://user-images.githubusercontent.com/76751931/125207840-14142f80-e28f-11eb-8366-91d1f1ad0099.png)
